UPDATE assets SET bid = 53.7, offer = 59.3 WHERE id = 1; -- Arsenal (EPL)
UPDATE assets SET bid = 30.6, offer = 33.9 WHERE id = 2; -- Man City (EPL)
UPDATE assets SET bid = 4.0, offer = 4.4 WHERE id = 3; -- Liverpool (EPL)
UPDATE assets SET bid = 4.5, offer = 5.0 WHERE id = 4; -- Chelsea (EPL)
UPDATE assets SET bid = 1.1, offer = 1.2 WHERE id = 5; -- Man Utd (EPL)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 6; -- Tottenham (EPL)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 7; -- Sunderland (EPL)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 8; -- Bournemouth (EPL)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 9; -- Crystal Palace (EPL)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 10; -- Newcastle (EPL)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 11; -- Brighton (EPL)
UPDATE assets SET bid = 3.7, offer = 4.0 WHERE id = 12; -- Aston Villa (EPL)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 13; -- Nottm Forest (EPL)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 14; -- Everton (EPL)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 15; -- West Ham (EPL)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 16; -- Fulham (EPL)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 17; -- Wolves (EPL)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 18; -- Brentford (EPL)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 19; -- Leeds (EPL)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 20; -- Burnley (EPL)

UPDATE assets SET bid = 21.9, offer = 24.2 WHERE id = 101; -- Arsenal (UCL)
UPDATE assets SET bid = 15.8, offer = 17.5 WHERE id = 102; -- Bayern Munich (UCL)
UPDATE assets SET bid = 13.6, offer = 15.0 WHERE id = 103; -- PSG (UCL)
UPDATE assets SET bid = 7.9, offer = 8.8 WHERE id = 104; -- Liverpool (UCL)
UPDATE assets SET bid = 10.6, offer = 11.7 WHERE id = 105; -- Man City (UCL)
UPDATE assets SET bid = 9.5, offer = 10.5 WHERE id = 106; -- Barcelona (UCL)
UPDATE assets SET bid = 10.6, offer = 11.7 WHERE id = 107; -- Real Madrid (UCL)
UPDATE assets SET bid = 5.6, offer = 6.2 WHERE id = 108; -- Chelsea (UCL)
UPDATE assets SET bid = 3.3, offer = 3.6 WHERE id = 109; -- Inter Milan (UCL)
UPDATE assets SET bid = 1.9, offer = 2.1 WHERE id = 110; -- Newcastle (UCL)
UPDATE assets SET bid = 2.8, offer = 3.1 WHERE id = 111; -- Atletico Madrid (UCL)
UPDATE assets SET bid = 1.9, offer = 2.1 WHERE id = 112; -- Tottenham (UCL)
UPDATE assets SET bid = 1.9, offer = 2.1 WHERE id = 113; -- Borussia Dortmund (UCL)
UPDATE assets SET bid = 2.3, offer = 2.6 WHERE id = 114; -- Napoli (UCL)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 115; -- Galatasaray (UCL)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 116; -- Atalanta (UCL)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 117; -- Juventus (UCL)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 118; -- Sporting Lisbon (UCL)
UPDATE assets SET bid = 1.4, offer = 1.6 WHERE id = 119; -- Bayer Leverkusen (UCL)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 120; -- PSV (UCL)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 121; -- Marseille (UCL)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 122; -- Monaco (UCL)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 123; -- Athletic Bilbao (UCL)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 124; -- Villarreal (UCL)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 125; -- Eintracht Frankfurt (UCL)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 126; -- Benfica (UCL)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 127; -- Olympiakos (UCL)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 128; -- Club Brugge (UCL)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 129; -- Union St Gilloise (UCL)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 130; -- FK Qarabag (UCL)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 131; -- Bodo Glimt (UCL)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 132; -- Ajax (UCL)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 133; -- Slavia Prague (UCL)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 134; -- FC Copenhagen (UCL)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 135; -- AEP Paphos (UCL)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 136; -- Kairat Almaty (UCL)

UPDATE assets SET bid = 17.3, offer = 19.1 WHERE id = 201; -- Spain (WC)
UPDATE assets SET bid = 14.6, offer = 16.2 WHERE id = 202; -- England (WC)
UPDATE assets SET bid = 10.6, offer = 11.7 WHERE id = 203; -- France (WC)
UPDATE assets SET bid = 10.6, offer = 11.7 WHERE id = 204; -- Brazil (WC)
UPDATE assets SET bid = 10.6, offer = 11.7 WHERE id = 205; -- Argentina (WC)
UPDATE assets SET bid = 7.9, offer = 8.8 WHERE id = 206; -- Portugal (WC)
UPDATE assets SET bid = 7.3, offer = 8.1 WHERE id = 207; -- Germany (WC)
UPDATE assets SET bid = 4.5, offer = 5.0 WHERE id = 208; -- Netherlands (WC)
UPDATE assets SET bid = 3.7, offer = 4.0 WHERE id = 209; -- Norway (WC)
UPDATE assets SET bid = 2.8, offer = 3.1 WHERE id = 210; -- Italy (WC)
UPDATE assets SET bid = 2.8, offer = 3.1 WHERE id = 211; -- Belgium (WC)
UPDATE assets SET bid = 1.4, offer = 1.6 WHERE id = 212; -- Uruguay (WC)
UPDATE assets SET bid = 1.9, offer = 2.1 WHERE id = 213; -- Colombia (WC)
UPDATE assets SET bid = 1.4, offer = 1.6 WHERE id = 214; -- Mexico (WC)
UPDATE assets SET bid = 1.2, offer = 1.3 WHERE id = 215; -- USA (WC)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 216; -- Japan (WC)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 217; -- Croatia (WC)
UPDATE assets SET bid = 1.2, offer = 1.3 WHERE id = 218; -- Ecuador (WC)
UPDATE assets SET bid = 1.2, offer = 1.3 WHERE id = 219; -- Morocco (WC)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 220; -- Switzerland (WC)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 221; -- Austria (WC)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 222; -- Senegal (WC)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 223; -- Denmark (WC)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 224; -- Sweden (WC)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 225; -- Ivory Coast (WC)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 226; -- Poland (WC)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 227; -- Turkey (WC)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 228; -- Canada (WC)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 229; -- Egypt (WC)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 230; -- Paraguay (WC)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 231; -- Ukraine (WC)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 232; -- Algeria (WC)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 233; -- South Korea (WC)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 234; -- Romania (WC)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 235; -- Australia (WC)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 236; -- Scotland (WC)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 237; -- Ghana (WC)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 238; -- Iran (WC)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 239; -- Wales (WC)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 240; -- Tunisia (WC)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 241; -- Slovakia (WC)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 242; -- Bolivia (WC)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 243; -- Czech Republic (WC)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 244; -- Qatar (WC)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 245; -- Republic of Ireland (WC)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 246; -- New Zealand (WC)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 247; -- Saudi Arabia (WC)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 248; -- North Macedonia (WC)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 249; -- DR Congo (WC)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 250; -- Panama (WC)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 251; -- Albania (WC)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 252; -- Northern Ireland (WC)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 253; -- Iraq (WC)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 254; -- Kosovo (WC)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 255; -- Curacao (WC)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 256; -- Cape Verde (WC)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 257; -- Jamaica (WC)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 258; -- Suriname (WC)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 259; -- Jordan (WC)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 260; -- Haiti (WC)

UPDATE assets SET bid = 45.2, offer = 50.0 WHERE id = 301; -- AL Hilal (SPL)
UPDATE assets SET bid = 38.0, offer = 42.0 WHERE id = 302; -- Al-Nassr Riyadh (SPL)
UPDATE assets SET bid = 6.3, offer = 7.0 WHERE id = 303; -- Al Qadisiyah FC (SPL)
UPDATE assets SET bid = 7.3, offer = 8.1 WHERE id = 304; -- Al Ittihad Jeddah (SPL)
UPDATE assets SET bid = 9.5, offer = 10.5 WHERE id = 305; -- Al Ahli Jeddah (SPL)
UPDATE assets SET bid = 3.7, offer = 4.0 WHERE id = 306; -- Al Taawon (SPL)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 307; -- Al Khaleej Saihat (SPL)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 308; -- Neom SC (SPL)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 309; -- Al Ittifaq Dammam (SPL)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 310; -- Al Kholood Ar Rass (SPL)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 311; -- Al Shabab (SPL)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 312; -- Al Riyadh (SPL)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 313; -- Al Fateh SC (SPL)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 314; -- Al Feiha (SPL)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 315; -- Al Hazm (SPL)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 316; -- Al Akhdoud (SPL)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 317; -- Damac FC (SPL)
UPDATE assets SET bid = 0.1, offer = 0.2 WHERE id = 318; -- Al Najma (SPL)

UPDATE assets SET bid = 70.4, offer = 77.8 WHERE id = 401; -- Lando Norris (F1)
UPDATE assets SET bid = 5.6, offer = 6.2 WHERE id = 402; -- Oscar Piastri (F1)
UPDATE assets SET bid = 20.7, offer = 22.8 WHERE id = 403; -- Max Verstappen (F1)
