
WITH updates (asset_name, market_name, new_buy, new_sell) AS (
    VALUES
    ('Arsenal', 'Premier League Performance Index', 80.8, 73.1),
    ('Man City', 'Premier League Performance Index', 20.2, 18.3),
    ('Liverpool', 'Premier League Performance Index', 0.2, 0.1),
    ('Chelsea', 'Premier League Performance Index', 0.2, 0.1),
    ('Man Utd', 'Premier League Performance Index', 0.2, 0.1),
    ('Tottenham', 'Premier League Performance Index', 0.2, 0.1),
    ('Sunderland', 'Premier League Performance Index', 0.2, 0.1),
    ('Bournemouth', 'Premier League Performance Index', 0.2, 0.1),
    ('Crystal Palace', 'Premier League Performance Index', 0.2, 0.1),
    ('Newcastle', 'Premier League Performance Index', 0.2, 0.1),
    ('Brighton', 'Premier League Performance Index', 0.2, 0.1),
    ('Aston Villa', 'Premier League Performance Index', 3.5, 3.2),
    ('Nottm Forest', 'Premier League Performance Index', 0.2, 0.1),
    ('Everton', 'Premier League Performance Index', 0.2, 0.1),
    ('West Ham', 'Premier League Performance Index', 0.2, 0.1),
    ('Fulham', 'Premier League Performance Index', 0.2, 0.1),
    ('Wolves', 'Premier League Performance Index', 0.2, 0.1),
    ('Brentford', 'Premier League Performance Index', 0.2, 0.1),
    ('Leeds', 'Premier League Performance Index', 0.2, 0.1),
    ('Burnley', 'Premier League Performance Index', 0.2, 0.1),
    ('Arsenal', 'Champions League Performance Index', 23.3, 21.1),
    ('Bayern Munich', 'Champions League Performance Index', 19.1, 17.3),
    ('PSG', 'Champions League Performance Index', 13.1, 11.9),
    ('Liverpool', 'Champions League Performance Index', 9.5, 8.6),
    ('Man City', 'Champions League Performance Index', 15, 13.6),
    ('Barcelona', 'Champions League Performance Index', 10.5, 9.5),
    ('Real Madrid', 'Champions League Performance Index', 9.5, 8.6),
    ('Chelsea', 'Champions League Performance Index', 5.5, 5),
    ('Inter Milan', 'Champions League Performance Index', 3.6, 3.3),
    ('Newcastle', 'Champions League Performance Index', 2.1, 1.9),
    ('Atletico Madrid', 'Champions League Performance Index', 3.1, 2.8),
    ('Tottenham', 'Champions League Performance Index', 2.1, 1.9),
    ('Borussia Dortmund', 'Champions League Performance Index', 1.6, 1.4),
    ('Napoli', 'Champions League Performance Index', 2.1, 1.9),
    ('Galatasaray', 'Champions League Performance Index', 0.2, 0.1),
    ('Atalanta', 'Champions League Performance Index', 1.3, 1.2),
    ('Juventus', 'Champions League Performance Index', 0.2, 0.1),
    ('Sporting Lisbon', 'Champions League Performance Index', 0.2, 0.1),
    ('Bayer Leverkusen', 'Champions League Performance Index', 0.2, 0.1),
    ('PSV', 'Champions League Performance Index', 0.2, 0.1),
    ('Marseille', 'Champions League Performance Index', 0.2, 0.1),
    ('Monaco', 'Champions League Performance Index', 0.2, 0.1),
    ('Athletic Bilbao', 'Champions League Performance Index', 0.2, 0.1),
    ('Villarreal', 'Champions League Performance Index', 0.2, 0.1),
    ('Eintracht Frankfurt', 'Champions League Performance Index', 0.2, 0.1),
    ('Benfica', 'Champions League Performance Index', 0.2, 0.1),
    ('Olympiakos', 'Champions League Performance Index', 0.2, 0.1),
    ('Club Brugge', 'Champions League Performance Index', 0.2, 0.1),
    ('Union St Gilloise', 'Champions League Performance Index', 0.2, 0.1),
    ('FK Qarabag', 'Champions League Performance Index', 0.2, 0.1),
    ('Bodo Glimt', 'Champions League Performance Index', 0.2, 0.1),
    ('Ajax', 'Champions League Performance Index', 0.2, 0.1),
    ('Slavia Prague', 'Champions League Performance Index', 0.2, 0.1),
    ('FC Copenhagen', 'Champions League Performance Index', 0.2, 0.1),
    ('AEP Paphos', 'Champions League Performance Index', 0.2, 0.1),
    ('Kairat Almaty', 'Champions League Performance Index', 0.2, 0.1),
    ('Spain', 'World Cup Performance Index', 19.1, 17.3),
    ('England', 'World Cup Performance Index', 16.2, 14.6),
    ('France', 'World Cup Performance Index', 11.7, 10.6),
    ('Brazil', 'World Cup Performance Index', 11.7, 10.6),
    ('Argentina', 'World Cup Performance Index', 11.7, 10.6),
    ('Portugal', 'World Cup Performance Index', 8.8, 7.9),
    ('Germany', 'World Cup Performance Index', 8.1, 7.3),
    ('Netherlands', 'World Cup Performance Index', 5, 4.5),
    ('Norway', 'World Cup Performance Index', 4, 3.7),
    ('Italy', 'World Cup Performance Index', 3.1, 2.8),
    ('Belgium', 'World Cup Performance Index', 3.1, 2.8),
    ('Uruguay', 'World Cup Performance Index', 1.6, 1.4),
    ('Colombia', 'World Cup Performance Index', 2.1, 1.9),
    ('Mexico', 'World Cup Performance Index', 1.6, 1.4),
    ('USA', 'World Cup Performance Index', 1.3, 1.2),
    ('Japan', 'World Cup Performance Index', 0.2, 0.1),
    ('Croatia', 'World Cup Performance Index', 0.2, 0.1),
    ('Ecuador', 'World Cup Performance Index', 1.3, 1.2),
    ('Morocco', 'World Cup Performance Index', 1.3, 1.2),
    ('Switzerland', 'World Cup Performance Index', 0.2, 0.1),
    ('Austria', 'World Cup Performance Index', 0.2, 0.1),
    ('Senegal', 'World Cup Performance Index', 0.2, 0.1),
    ('Denmark', 'World Cup Performance Index', 0.2, 0.1),
    ('Sweden', 'World Cup Performance Index', 0.2, 0.1),
    ('Ivory Coast', 'World Cup Performance Index', 0.2, 0.1),
    ('Poland', 'World Cup Performance Index', 0.2, 0.1),
    ('Turkey', 'World Cup Performance Index', 0.2, 0.1),
    ('Canada', 'World Cup Performance Index', 0.2, 0.1),
    ('Egypt', 'World Cup Performance Index', 0.2, 0.1),
    ('Paraguay', 'World Cup Performance Index', 0.2, 0.1),
    ('Ukraine', 'World Cup Performance Index', 0.2, 0.1),
    ('Algeria', 'World Cup Performance Index', 0.2, 0.1),
    ('South Korea', 'World Cup Performance Index', 0.2, 0.1),
    ('Romania', 'World Cup Performance Index', 0.2, 0.1),
    ('Australia', 'World Cup Performance Index', 0.2, 0.1),
    ('Scotland', 'World Cup Performance Index', 0.2, 0.1),
    ('Ghana', 'World Cup Performance Index', 0.2, 0.1),
    ('Iran', 'World Cup Performance Index', 0.2, 0.1),
    ('Wales', 'World Cup Performance Index', 0.2, 0.1),
    ('Tunisia', 'World Cup Performance Index', 0.2, 0.1),
    ('Slovakia', 'World Cup Performance Index', 0.2, 0.1),
    ('Bolivia', 'World Cup Performance Index', 0.2, 0.1),
    ('Czech Republic', 'World Cup Performance Index', 0.2, 0.1),
    ('Qatar', 'World Cup Performance Index', 0.2, 0.1),
    ('Republic of Ireland', 'World Cup Performance Index', 0.2, 0.1),
    ('New Zealand', 'World Cup Performance Index', 0.2, 0.1),
    ('Saudi Arabia', 'World Cup Performance Index', 0.2, 0.1),
    ('North Macedonia', 'World Cup Performance Index', 0.2, 0.1),
    ('DR Congo', 'World Cup Performance Index', 0.2, 0.1),
    ('Panama', 'World Cup Performance Index', 0.2, 0.1),
    ('Albania', 'World Cup Performance Index', 0.2, 0.1),
    ('Northern Ireland', 'World Cup Performance Index', 0.2, 0.1),
    ('Iraq', 'World Cup Performance Index', 0.2, 0.1),
    ('Kosovo', 'World Cup Performance Index', 0.2, 0.1),
    ('Curacao', 'World Cup Performance Index', 0.2, 0.1),
    ('Cape Verde', 'World Cup Performance Index', 0.2, 0.1),
    ('Jamaica', 'World Cup Performance Index', 0.2, 0.1),
    ('Suriname', 'World Cup Performance Index', 0.2, 0.1),
    ('Jordan', 'World Cup Performance Index', 0.2, 0.1),
    ('Haiti', 'World Cup Performance Index', 0.2, 0.1),
    ('AL Hilal', 'Saudi Pro League Performance Index', 72.9, 66),
    ('Al-Nassr Riyadh', 'Saudi Pro League Performance Index', 24.2, 21.9),
    ('Al Qadisiyah FC', 'Saudi Pro League Performance Index', 6.2, 5.6),
    ('Al Ittihad Jeddah', 'Saudi Pro League Performance Index', 4, 3.7),
    ('Al Ahli Jeddah', 'Saudi Pro League Performance Index', 9.5, 8.6),
    ('Al Taawon', 'Saudi Pro League Performance Index', 4, 3.7),
    ('Al Khaleej Saihat', 'Saudi Pro League Performance Index', 0.2, 0.1),
    ('Neom SC', 'Saudi Pro League Performance Index', 0.2, 0.1),
    ('Al Ittifaq Dammam', 'Saudi Pro League Performance Index', 0.2, 0.1),
    ('Al Kholood Ar Rass', 'Saudi Pro League Performance Index', 0.2, 0.1),
    ('Al Shabab', 'Saudi Pro League Performance Index', 0.2, 0.1),
    ('Al Riyadh', 'Saudi Pro League Performance Index', 0.2, 0.1),
    ('Al Fateh SC', 'Saudi Pro League Performance Index', 0.2, 0.1),
    ('Al Feiha', 'Saudi Pro League Performance Index', 0.2, 0.1),
    ('Al Hazm', 'Saudi Pro League Performance Index', 0.2, 0.1),
    ('Al Akhdoud', 'Saudi Pro League Performance Index', 0.2, 0.1),
    ('Damac FC', 'Saudi Pro League Performance Index', 0.2, 0.1),
    ('Al Najma', 'Saudi Pro League Performance Index', 0.2, 0.1),
    ('Lando Norris', 'Formula 1 Drivers Performance Index', 77.8, 70.4),
    ('Oscar Piastri', 'Formula 1 Drivers Performance Index', 6.2, 5.6),
    ('Max Verstappen', 'Formula 1 Drivers Performance Index', 22.8, 20.7),
    ('Oklahoma City Thunder', 'NBA Performance Index', 48.8, 44.2),
    ('Denver Nuggets', 'NBA Performance Index', 13.1, 11.9),
    ('Houston Rockets', 'NBA Performance Index', 8.1, 7.3),
    ('Los Angeles Lakers', 'NBA Performance Index', 3.6, 3.3),
    ('Cleveland Cavaliers', 'NBA Performance Index', 4, 3.7),
    ('New York Knicks', 'NBA Performance Index', 8.1, 7.3),
    ('Detroit Pistons', 'NBA Performance Index', 5.5, 5),
    ('Golden State Warriors', 'NBA Performance Index', 2.9, 2.6),
    ('Minnesota Timberwolves', 'NBA Performance Index', 3.4, 3.1),
    ('Orlando Magic', 'NBA Performance Index', 2.6, 2.3),
    ('San Antonio Spurs', 'NBA Performance Index', 8.1, 7.3),
    ('Atlanta Hawks', 'NBA Performance Index', 0.2, 0.1),
    ('Philadelphia 76ers', 'NBA Performance Index', 2.1, 1.9),
    ('Boston Celtics', 'NBA Performance Index', 5, 4.5),
    ('Miami Heat', 'NBA Performance Index', 1.3, 1.2),
    ('Toronto Raptors', 'NBA Performance Index', 0.2, 0.1),
    ('Chicago Bulls', 'NBA Performance Index', 0.2, 0.1),
    ('Milwaukee Bucks', 'NBA Performance Index', 0.2, 0.1),
    ('Phoenix Suns', 'NBA Performance Index', 0.2, 0.1),
    ('Dallas Mavericks', 'NBA Performance Index', 0.2, 0.1),
    ('Memphis Grizzlies', 'NBA Performance Index', 0.2, 0.1),
    ('Portland Trail Blazers', 'NBA Performance Index', 0.2, 0.1),
    ('Los Angeles Clippers', 'NBA Performance Index', 0.2, 0.1),
    ('Sacramento Kings', 'NBA Performance Index', 0.2, 0.1),
    ('Indiana Pacers', 'NBA Performance Index', 0.2, 0.1),
    ('New Orleans Pelicans', 'NBA Performance Index', 0.2, 0.1),
    ('Charlotte Hornets', 'NBA Performance Index', 0.2, 0.1),
    ('Utah Jazz', 'NBA Performance Index', 0.2, 0.1),
    ('Washington Wizards', 'NBA Performance Index', 0.2, 0.1),
    ('Brooklyn Nets', 'NBA Performance Index', 0.2, 0.1),
    ('Los Angeles Rams', 'NFL Performance Index', 32.8, 29.7),
    ('Philadelphia Eagles', 'NFL Performance Index', 0.2, 0.1),
    ('Buffalo Bills', 'NFL Performance Index', 0.2, 0.1),
    ('Seattle Seahawks', 'NFL Performance Index', 42, 38),
    ('New England Patriots', 'NFL Performance Index', 30.9, 27.9),
    ('Green Bay Packers', 'NFL Performance Index', 0.2, 0.1),
    ('Denver Broncos', 'NFL Performance Index', 8.1, 7.3),
    ('Baltimore Ravens', 'NFL Performance Index', 0.2, 0.1),
    ('Kansas City Chiefs', 'NFL Performance Index', 0.2, 0.1),
    ('Detroit Lions', 'NFL Performance Index', 0.2, 0.1),
    ('Indianapolis Colts', 'NFL Performance Index', 0.2, 0.1),
    ('San Francisco 49ers', 'NFL Performance Index', 0.2, 0.1),
    ('Houston Texans', 'NFL Performance Index', 0.2, 0.1),
    ('Chicago Bears', 'NFL Performance Index', 0.2, 0.1),
    ('Tampa Bay Buccaneers', 'NFL Performance Index', 0.2, 0.1),
    ('Los Angeles Chargers', 'NFL Performance Index', 0.2, 0.1),
    ('Jacksonville Jaguars', 'NFL Performance Index', 0.2, 0.1),
    ('Cincinnati Bengals', 'NFL Performance Index', 0.2, 0.1),
    ('Pittsburgh Steelers', 'NFL Performance Index', 0.2, 0.1),
    ('Dallas Cowboys', 'NFL Performance Index', 0.2, 0.1),
    ('Carolina Panthers', 'NFL Performance Index', 0.2, 0.1),
    ('Miami Dolphins', 'NFL Performance Index', 0.2, 0.1),
    ('Cleveland Browns', 'NFL Performance Index', 0.2, 0.1),
    ('Atlanta Falcons', 'NFL Performance Index', 0.2, 0.1),
    ('Washington Commanders', 'NFL Performance Index', 0.2, 0.1),
    ('Minnesota Vikings', 'NFL Performance Index', 0.2, 0.1),
    ('New York Jets', 'NFL Performance Index', 0.2, 0.1),
    ('India', 'T20 World Cup Performance Index', 44.1, 39.9),
    ('Australia', 'T20 World Cup Performance Index', 21, 19),
    ('South Africa', 'T20 World Cup Performance Index', 16.2, 14.6),
    ('England', 'T20 World Cup Performance Index', 19.1, 17.3),
    ('Pakistan', 'T20 World Cup Performance Index', 6.2, 5.6),
    ('New Zealand', 'T20 World Cup Performance Index', 6.2, 5.6),
    ('West Indies', 'T20 World Cup Performance Index', 5, 4.5),
    ('Afghanistan', 'T20 World Cup Performance Index', 4, 3.7),
    ('Sri Lanka', 'T20 World Cup Performance Index', 2.6, 2.3),
    ('Bangladesh', 'T20 World Cup Performance Index', 0.2, 0.1),
    ('Ireland', 'T20 World Cup Performance Index', 0.2, 0.1),
    ('Zimbabwe', 'T20 World Cup Performance Index', 0.2, 0.1),
    ('USA', 'T20 World Cup Performance Index', 0.2, 0.1),
    ('Netherlands', 'T20 World Cup Performance Index', 0.2, 0.1),
    ('Nepal', 'T20 World Cup Performance Index', 0.2, 0.1),
    ('Canada', 'T20 World Cup Performance Index', 0.2, 0.1),
    ('UAE', 'T20 World Cup Performance Index', 0.2, 0.1),
    ('Oman', 'T20 World Cup Performance Index', 0.2, 0.1),
    ('Namibia', 'T20 World Cup Performance Index', 0.2, 0.1),
    ('Italy', 'T20 World Cup Performance Index', 0.2, 0.1),
    ('Israel', 'Eurovision Performance Index', 16.4, 14.8),
    ('Finland', 'Eurovision Performance Index', 17.5, 15.8),
    ('Sweden', 'Eurovision Performance Index', 15.4, 14),
    ('Ukraine', 'Eurovision Performance Index', 8.8, 7.9),
    ('Italy', 'Eurovision Performance Index', 8.1, 7.3),
    ('Luxembourg', 'Eurovision Performance Index', 7.8, 7),
    ('France', 'Eurovision Performance Index', 5, 4.5),
    ('Norway', 'Eurovision Performance Index', 5.3, 4.8),
    ('Belgium', 'Eurovision Performance Index', 5, 4.5),
    ('Bulgaria', 'Eurovision Performance Index', 4.6, 4.1),
    ('Denmark', 'Eurovision Performance Index', 4.6, 4.1),
    ('Croatia', 'Eurovision Performance Index', 4.4, 4),
    ('Cyprus', 'Eurovision Performance Index', 4.4, 4),
    ('Lithuania', 'Eurovision Performance Index', 4.4, 4),
    ('Netherlands', 'Eurovision Performance Index', 0.2, 0.1),
    ('Moldova', 'Eurovision Performance Index', 4.2, 3.8),
    ('United Kingdom', 'Eurovision Performance Index', 4, 3.7),
    ('Romania', 'Eurovision Performance Index', 3.9, 3.5),
    ('Estonia', 'Eurovision Performance Index', 4, 3.7),
    ('Greece', 'Eurovision Performance Index', 4, 3.7),
    ('Poland', 'Eurovision Performance Index', 4, 3.7),
    ('Switzerland', 'Eurovision Performance Index', 3.9, 3.5),
    ('Spain', 'Eurovision Performance Index', 3.9, 3.5),
    ('Latvia', 'Eurovision Performance Index', 3.9, 3.5),
    ('Montenegro', 'Eurovision Performance Index', 3.9, 3.5),
    ('Borneo', 'Indonesia Super League Performance Index', 33.9, 30.6),
    ('Persija Jakarta', 'Indonesia Super League Performance Index', 22.1, 20),
    ('Persib Bandung', 'Indonesia Super League Performance Index', 40.4, 36.5),
    ('Malut United', 'Indonesia Super League Performance Index', 9.5, 8.6),
    ('PSIM Yogyakarta', 'Indonesia Super League Performance Index', 2.6, 2.3),
    ('Persita Tangerang', 'Indonesia Super League Performance Index', 3.1, 2.8),
    ('Bhayangkara United', 'Indonesia Super League Performance Index', 0.2, 0.1),
    ('PSM Makassar', 'Indonesia Super League Performance Index', 0.2, 0.1),
    ('Persebaya 1927', 'Indonesia Super League Performance Index', 1.6, 1.4),
    ('Arema', 'Indonesia Super League Performance Index', 0.2, 0.1),
    ('Bali United Pusam', 'Indonesia Super League Performance Index', 1.3, 1.2),
    ('Persik Kediri', 'Indonesia Super League Performance Index', 0.2, 0.1),
    ('Madura United', 'Indonesia Super League Performance Index', 0.2, 0.1),
    ('Dewa United', 'Indonesia Super League Performance Index', 0.2, 0.1),
    ('PSBS Biak', 'Indonesia Super League Performance Index', 0.2, 0.1),
    ('Persijap Jepara', 'Indonesia Super League Performance Index', 0.2, 0.1),
    ('Semen Padang', 'Indonesia Super League Performance Index', 0.2, 0.1),
    ('Persis Solo', 'Indonesia Super League Performance Index', 0.2, 0.1)
)
UPDATE market_index_trading_assets mita
SET buy = u.new_buy, sell = u.new_sell
FROM updates u
JOIN assets a ON a.name = u.asset_name
JOIN market_indexes mi ON mi.name = u.market_name
JOIN market_index_seasons mis ON mis.market_index_id = mi.id
WHERE mita.asset_id = a.id
  AND mita.market_index_season_id = mis.id;
